/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShadowRollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchSchedulePayment"
      | "cancelRecurringSchedule"
      | "checkMySalary"
      | "createRecurringSchedule"
      | "employerPool"
      | "executeRecurring"
      | "fundPool"
      | "getEncryptedBalance"
      | "getRecipientList"
      | "getRecurringRecipients"
      | "hasSalary"
      | "owner"
      | "recurringSchedules"
      | "revokePayment"
      | "schedulePayment"
      | "token"
      | "transferOwnership"
      | "unshield"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchPaymentScheduled"
      | "OwnershipTransferred"
      | "PaymentClaimed"
      | "PaymentRevoked"
      | "PaymentScheduled"
      | "PoolFunded"
      | "RecurringPaymentExecuted"
      | "RecurringScheduleCancelled"
      | "RecurringScheduleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchSchedulePayment",
    values: [AddressLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecurringSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkMySalary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createRecurringSchedule",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "employerPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRecurring",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecurringRecipients",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSalary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recurringSchedules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePayment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "schedulePayment",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unshield",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchSchedulePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecurringSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkMySalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRecurringSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employerPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRecurring",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecurringRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasSalary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recurringSchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "schedulePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unshield", data: BytesLike): Result;
}

export namespace BatchPaymentScheduledEvent {
  export type InputTuple = [employer: AddressLike, count: BigNumberish];
  export type OutputTuple = [employer: string, count: bigint];
  export interface OutputObject {
    employer: string;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentClaimedEvent {
  export type InputTuple = [recipient: AddressLike];
  export type OutputTuple = [recipient: string];
  export interface OutputObject {
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRevokedEvent {
  export type InputTuple = [employer: AddressLike, recipient: AddressLike];
  export type OutputTuple = [employer: string, recipient: string];
  export interface OutputObject {
    employer: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentScheduledEvent {
  export type InputTuple = [employer: AddressLike, recipient: AddressLike];
  export type OutputTuple = [employer: string, recipient: string];
  export interface OutputObject {
    employer: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [employer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [employer: string, amount: bigint];
  export interface OutputObject {
    employer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringPaymentExecutedEvent {
  export type InputTuple = [employer: AddressLike, recipient: AddressLike];
  export type OutputTuple = [employer: string, recipient: string];
  export interface OutputObject {
    employer: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringScheduleCancelledEvent {
  export type InputTuple = [employer: AddressLike, recipient: AddressLike];
  export type OutputTuple = [employer: string, recipient: string];
  export interface OutputObject {
    employer: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecurringScheduleCreatedEvent {
  export type InputTuple = [
    employer: AddressLike,
    recipient: AddressLike,
    intervalSeconds: BigNumberish
  ];
  export type OutputTuple = [
    employer: string,
    recipient: string,
    intervalSeconds: bigint
  ];
  export interface OutputObject {
    employer: string;
    recipient: string;
    intervalSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShadowRoll extends BaseContract {
  connect(runner?: ContractRunner | null): ShadowRoll;
  waitForDeployment(): Promise<this>;

  interface: ShadowRollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchSchedulePayment: TypedContractMethod<
    [recipients: AddressLike[], encryptedAmounts: BytesLike[]],
    [void],
    "nonpayable"
  >;

  cancelRecurringSchedule: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  checkMySalary: TypedContractMethod<[], [boolean], "view">;

  createRecurringSchedule: TypedContractMethod<
    [
      recipient: AddressLike,
      encryptedAmount: BytesLike,
      intervalSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  employerPool: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  executeRecurring: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  fundPool: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEncryptedBalance: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getRecipientList: TypedContractMethod<[], [string[]], "view">;

  getRecurringRecipients: TypedContractMethod<[], [string[]], "view">;

  hasSalary: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recurringSchedules: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        encryptedAmount: string;
        intervalSeconds: bigint;
        lastExecuted: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  revokePayment: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  schedulePayment: TypedContractMethod<
    [recipient: AddressLike, encryptedAmount: BytesLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unshield: TypedContractMethod<
    [amountToWithdraw: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchSchedulePayment"
  ): TypedContractMethod<
    [recipients: AddressLike[], encryptedAmounts: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelRecurringSchedule"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkMySalary"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "createRecurringSchedule"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      encryptedAmount: BytesLike,
      intervalSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "employerPool"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeRecurring"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecipientList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRecurringRecipients"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasSalary"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recurringSchedules"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        encryptedAmount: string;
        intervalSeconds: bigint;
        lastExecuted: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokePayment"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schedulePayment"
  ): TypedContractMethod<
    [recipient: AddressLike, encryptedAmount: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unshield"
  ): TypedContractMethod<
    [amountToWithdraw: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchPaymentScheduled"
  ): TypedContractEvent<
    BatchPaymentScheduledEvent.InputTuple,
    BatchPaymentScheduledEvent.OutputTuple,
    BatchPaymentScheduledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentClaimed"
  ): TypedContractEvent<
    PaymentClaimedEvent.InputTuple,
    PaymentClaimedEvent.OutputTuple,
    PaymentClaimedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRevoked"
  ): TypedContractEvent<
    PaymentRevokedEvent.InputTuple,
    PaymentRevokedEvent.OutputTuple,
    PaymentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentScheduled"
  ): TypedContractEvent<
    PaymentScheduledEvent.InputTuple,
    PaymentScheduledEvent.OutputTuple,
    PaymentScheduledEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "RecurringPaymentExecuted"
  ): TypedContractEvent<
    RecurringPaymentExecutedEvent.InputTuple,
    RecurringPaymentExecutedEvent.OutputTuple,
    RecurringPaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RecurringScheduleCancelled"
  ): TypedContractEvent<
    RecurringScheduleCancelledEvent.InputTuple,
    RecurringScheduleCancelledEvent.OutputTuple,
    RecurringScheduleCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecurringScheduleCreated"
  ): TypedContractEvent<
    RecurringScheduleCreatedEvent.InputTuple,
    RecurringScheduleCreatedEvent.OutputTuple,
    RecurringScheduleCreatedEvent.OutputObject
  >;

  filters: {
    "BatchPaymentScheduled(address,uint256)": TypedContractEvent<
      BatchPaymentScheduledEvent.InputTuple,
      BatchPaymentScheduledEvent.OutputTuple,
      BatchPaymentScheduledEvent.OutputObject
    >;
    BatchPaymentScheduled: TypedContractEvent<
      BatchPaymentScheduledEvent.InputTuple,
      BatchPaymentScheduledEvent.OutputTuple,
      BatchPaymentScheduledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentClaimed(address)": TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;
    PaymentClaimed: TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;

    "PaymentRevoked(address,address)": TypedContractEvent<
      PaymentRevokedEvent.InputTuple,
      PaymentRevokedEvent.OutputTuple,
      PaymentRevokedEvent.OutputObject
    >;
    PaymentRevoked: TypedContractEvent<
      PaymentRevokedEvent.InputTuple,
      PaymentRevokedEvent.OutputTuple,
      PaymentRevokedEvent.OutputObject
    >;

    "PaymentScheduled(address,address)": TypedContractEvent<
      PaymentScheduledEvent.InputTuple,
      PaymentScheduledEvent.OutputTuple,
      PaymentScheduledEvent.OutputObject
    >;
    PaymentScheduled: TypedContractEvent<
      PaymentScheduledEvent.InputTuple,
      PaymentScheduledEvent.OutputTuple,
      PaymentScheduledEvent.OutputObject
    >;

    "PoolFunded(address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "RecurringPaymentExecuted(address,address)": TypedContractEvent<
      RecurringPaymentExecutedEvent.InputTuple,
      RecurringPaymentExecutedEvent.OutputTuple,
      RecurringPaymentExecutedEvent.OutputObject
    >;
    RecurringPaymentExecuted: TypedContractEvent<
      RecurringPaymentExecutedEvent.InputTuple,
      RecurringPaymentExecutedEvent.OutputTuple,
      RecurringPaymentExecutedEvent.OutputObject
    >;

    "RecurringScheduleCancelled(address,address)": TypedContractEvent<
      RecurringScheduleCancelledEvent.InputTuple,
      RecurringScheduleCancelledEvent.OutputTuple,
      RecurringScheduleCancelledEvent.OutputObject
    >;
    RecurringScheduleCancelled: TypedContractEvent<
      RecurringScheduleCancelledEvent.InputTuple,
      RecurringScheduleCancelledEvent.OutputTuple,
      RecurringScheduleCancelledEvent.OutputObject
    >;

    "RecurringScheduleCreated(address,address,uint256)": TypedContractEvent<
      RecurringScheduleCreatedEvent.InputTuple,
      RecurringScheduleCreatedEvent.OutputTuple,
      RecurringScheduleCreatedEvent.OutputObject
    >;
    RecurringScheduleCreated: TypedContractEvent<
      RecurringScheduleCreatedEvent.InputTuple,
      RecurringScheduleCreatedEvent.OutputTuple,
      RecurringScheduleCreatedEvent.OutputObject
    >;
  };
}
